---
# ***Asignatura: Cienca de Datos***
---

## **Unidad 1**: Práctica - Librería NumPy

### ***Universidad Nacional de Chilecito***

---


La idea de esta práctica es ejercitar los puntos que vamos a necesitar para resolver el desafío.

Usaremos un resumen del dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data

En la siguiente carpeta se encuentran los diferentes DataSet que vamos a usar en la asignatura.

[Carpeta con Data Set que vamos a usar](https://drive.google.com/drive/folders/1MvILOMQLvogBHSDKEoTkwE6WPY-s1H07?usp=drive_link)

Deberás:

* Darle click derecho a la carpeta CienciaDatos y seleccionar la opción de Añadir acceso directo a Drive

* Seleccionar que se añada en Mi Unidad, dentro de Todas las ubicaciones

* y Listo
Con esto, ya tendrás acceso a los archivos que nosotros subamos siempre.

## Ejercicio 1
Leer los datos del archivo [/DataSet/sales_data_sample_excercise.csv](https://drive.google.com/file/d/1s_Z_oI1MQG6p2OeSiSG5VgeEvpdx2ZdF/view?usp=sharing)


Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres.

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.


Con ayuda del siguiente código podrás vincular tu cuenta de Google Drive.


In [1]:
from google.colab import drive
drive.mount('/content/drive')
pathCurso = '/content/drive/MyDrive/CienciaDatos/DataSet/'

Mounted at /content/drive


Con el siguiente comando podrás abrir el archivo que vamos a necesitar en ésta ocasión:

In [2]:
import numpy as np

# local:
data_location = pathCurso + 'sales_data_sample_excercise.csv'

In [3]:
print(data_location)

/content/drive/MyDrive/CienciaDatos/DataSet/sales_data_sample_excercise.csv


Con el siguiente código podrás importar el archivo:

In [4]:
data_type_default = np.genfromtxt(data_location, skip_header=1, delimiter='\t')
data_type_default

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

In [ ]:
import os

if os.path.exists(data_location):
    print(f"El archivo existe en la ruta: {data_location}")
else:
    print(f"¡Error! El archivo NO existe en la ruta: {data_location}")
    print("Por favor, asegúrate de que Google Drive esté montado y que el archivo esté en la ubicación correcta.")

In [ ]:
data_type_str = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)
data_type_str

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

In [ ]:
data_type_int = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= int)
data_type_int

array([[10107,  2871,     2,  2003,    -1,    -1],
       [10121,    -1,     5,  2003,    -1,    -1],
       [10134,    -1,     7,  2003,    -1,    -1],
       ...,
       [10386,    -1,     3,  2005,    -1,    -1],
       [10397,    -1,     3,  2005,    -1,    -1],
       [10414,    -1,     5,  2005,    -1,    -1]])

In [ ]:
data_type_float = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= float)
data_type_float

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

# Ejercicio 2 - Tipos

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

## Ejercicio 3 - Funciones de agregación

Sobre los datos de precios de ventas (columna SALES) calcular:

* mínimo

* máximo

* promedio

* cantidad

* suma

Ayuda: https://docs.scipy.org/doc/numpy-1.17.0/reference/routines.statistics.html

## Ejercicio 4 - Indexing

a) ¿Cuántas ventas se hicieron en USA?

Ayuda: boolean indexing

b) ¿Cuáles son los precios de las 5 ventas que están en las filas 6 a 10 del dataset?

Resolvamos usando array slicing y fancy indexing

Ayuda: recuerden `range` https://docs.python.org/3/library/functions.html#func-range